# Copyright © 2016-2017 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Cask is a trademark of Cask Data, Inc. All rights reserved.

FROM centos:6
MAINTAINER Cask Data <ops@cask.co>

# Copy files
# Setup ENV
# Install Chef
# Setup chef dir
# Install/run omnibus, java, and maven cookbooks

COPY . /var/tmp/coopr-build

ENV PATH /usr/local/bin:${PATH}
ENV COOPR_BUILD_PROJECTS coopr-cli coopr-provisioner coopr-server coopr-ui

RUN useradd -m coopr && \
  yum makecache && \
  yum install -y \
    curl \
    git \
    python && \
  curl -vL http://chef.io/chef/install.sh | bash -s && \
  mkdir -p /var/chef/cookbooks && \
  cd /var/chef/cookbooks && \
  touch .gitignore && git init && git add .gitignore && git commit -m 'Initial commit' && \
  knife cookbook site install maven 1.1.0 && \
  knife cookbook site install apt 2.4.0 && \
  knife cookbook site install build-essential 1.4.4 && \
  knife cookbook site install git 3.1.0 && \
  knife cookbook site install homebrew 1.9.0 && \
  knife cookbook site install pkgin 0.4.0 && \
  knife cookbook site install pkgutil 0.0.3 && \
  knife cookbook site install rbenv 1.7.1 && \
  knife cookbook site install windows 1.34.2 && \
  knife cookbook site install wix 1.1.0 && \
  knife cookbook site install yum-epel 0.4.0 && \
  knife cookbook site download 7-zip --force && \
  for tb in maven apt build-essential git homebrew pkgin pkgutil rbenv windows wix yum-epel 7-zip; do \
    tar xf ${tb}*.tar.gz ; \
    rm -f ${tb}*.tar.gz ; \
  done && \
  echo "name 'pkgin'" >> pkgin/metadata.rb && \
  git commit -am "HACK: Add name to pkgin's metadata" && \
  echo "name 'pkgutil'" >> pkgutil/metadata.rb && \
  git commit -am "HACK: Add name to pkgutil's metadata" && \
  knife cookbook site install omnibus 1.2.4 --skip-dependencies && \
  rm -f *.tar.gz && \
  mkdir -p /var/tmp/coopr-build && \
  chown -R coopr /var/tmp/coopr-build && \
  cd /var/tmp/coopr-build && \
  chef-solo -j /var/tmp/coopr-build/chef.json -o 'recipe[omnibus],recipe[maven]' && \
  gem install bundler --no-rdoc --no-ri && \
  chown -R coopr /opt && \
  su coopr -c "bundle install --binstubs" && \
  su coopr -c "git config --global user.email 'ops@cask.co' && git config --global user.name 'Cask Ops'" && \
  for project in ${COOPR_BUILD_PROJECTS} ; do \
    su coopr -c "bin/omnibus build ${project}" ; \
    rm -rf /opt/coopr ; \
  done
