# Copyright © 2016-2018 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Cask is a trademark of Cask Data, Inc. All rights reserved.

FROM centos:6
MAINTAINER Cask Data <ops@cask.co>

# Copy files
# Setup ENV
# Install Chef
# Setup chef dir
# Install/run omnibus, java, and maven cookbooks

COPY . /var/tmp/coopr-build

ENV PATH /usr/local/bin:${PATH}
ENV COOPR_BUILD_PROJECTS coopr-cli coopr-provisioner coopr-server coopr-ui

RUN useradd -m coopr && \
  yum makecache && \
  yum install -y \
    curl \
    git \
    python && \
  curl -vL http://chef.io/chef/install.sh | bash -s -- -v 12.22.5 && \
  mkdir -p /var/chef/cookbooks && \
  cd /var/chef/cookbooks && \
  touch .gitignore && git init && git add .gitignore && git commit -m 'Initial commit' && \
  knife cookbook site download ark 4.0.0 --force && \
  knife cookbook site download build-essential 8.2.1 --force && \
  knife cookbook site download chef-ingredient 2.3.2 --force && \
  knife cookbook site download chef-sugar 4.1.0 --force && \
  knife cookbook site download git 9.0.1 --force && \
  knife cookbook site download homebrew 5.0.8 --force && \
  knife cookbook site download java 2.2.1 --force && \
  knife cookbook site download maven 5.2.0 --force && \
  knife cookbook site download mingw 2.1.0 --force && \
  knife cookbook site download omnibus 5.7.2 --force && \
  knife cookbook site download remote_install 2.0.0 --force && \
  knife cookbook site download seven_zip 3.0.0 --force && \
  knife cookbook site download windows 5.1.1 --force && \
  knife cookbook site download wix 5.0.0 --force && \
  for tb in *.tar.gz; do tar xf ${tb}; rm -f ${tb}; done && \
  git add . && git commit -m 'Added cookbooks' && \
  mkdir -p /var/tmp/coopr-build && \
  chown -R coopr /var/tmp/coopr-build && \
  cd /var/tmp/coopr-build && \
  chef-solo -j /var/tmp/coopr-build/chef.json -o 'recipe[omnibus],recipe[java],recipe[maven]' && \
  export PATH=/opt/omnibus-toolchain/embedded/bin:$PATH && \
  chown -R coopr /opt && \
  su coopr -c "bundle install --binstubs" && \
  su coopr -c "git config --global user.email 'ops@cask.co' && git config --global user.name 'Cask Ops'" && \
  __failed= && \
  for project in ${COOPR_BUILD_PROJECTS}; do \
    su coopr -c "bin/omnibus build ${project}" || __failed+="${project} "; \
    rm -rf /opt/coopr ; \
  done && \
  if test -n "${__failed}"; then \
    echo "ERROR: Failed to build ${__failed}"; \
    exit 1; \
  fi
