# Copyright © 2016-2017 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Cask is a trademark of Cask Data, Inc. All rights reserved.

FROM centos:6
MAINTAINER Cask Data <ops@cask.co>

# Copy files
# Setup ENV
# Install Chef
# Setup chef dir
# Install/run omnibus, java, and maven cookbooks

COPY . /var/tmp/coopr-build

ENV PATH /usr/local/bin:${PATH}
ENV COOPR_BUILD_PROJECTS coopr-cli coopr-provisioner coopr-server coopr-ui

RUN useradd -m coopr && \
  yum makecache && \
  yum install -y \
    curl \
    git \
    python && \
  curl -vL http://chef.io/chef/install.sh | bash -s -- -v 12.10.24 && \
  mkdir -p /var/chef/cookbooks && \
  cd /var/chef/cookbooks && \
  touch .gitignore && git init && git add .gitignore && git commit -m 'Initial commit' && \
  knife cookbook site download 7-zip 1.0.2 --force && \
  knife cookbook site download apt 2.4.0 --force && \
  knife cookbook site download ark 0.9.0 --force && \
  knife cookbook site download build-essential 1.4.4 --force && \
  knife cookbook site download chef_handler 1.1.6 --force && \
  knife cookbook site download dmg 2.2.0 --force && \
  knife cookbook site download git 3.1.0 --force && \
  knife cookbook site download homebrew 1.9.0 --force && \
  knife cookbook site download java 1.21.2 --force && \
  knife cookbook site download maven 1.1.0 --force && \
  knife cookbook site download ohai 2.0.1 --force && \
  knife cookbook site download omnibus 1.2.4 --force && \
  knife cookbook site download pkgin 0.4.0 --force && \
  knife cookbook site download pkgutil 0.0.3 --force && \
  knife cookbook site download rbenv 1.7.1 --force && \
  knife cookbook site download runit 1.5.10 --force && \
  knife cookbook site download windows 1.34.2 --force && \
  knife cookbook site download wix 1.1.0 --force && \
  knife cookbook site download yum 3.2.2 --force && \
  knife cookbook site download yum-epel 0.4.0 --force && \
  for tb in *.tar.gz; do tar xf ${tb}; rm -f ${tb}; done && \
  git add . && git commit -m 'Added cookbooks' && \
  echo "name 'pkgin'" >> pkgin/metadata.rb && \
  git commit -am "HACK: Add name to pkgin's metadata" && \
  echo "name 'pkgutil'" >> pkgutil/metadata.rb && \
  git commit -am "HACK: Add name to pkgutil's metadata" && \
  mkdir -p /var/tmp/coopr-build && \
  chown -R coopr /var/tmp/coopr-build && \
  cd /var/tmp/coopr-build && \
  chef-solo -j /var/tmp/coopr-build/chef.json -o 'recipe[omnibus],recipe[maven]' && \
  gem install bundler --no-rdoc --no-ri && \
  chown -R coopr /opt && \
  su coopr -c "bundle install --binstubs" && \
  su coopr -c "git config --global user.email 'ops@cask.co' && git config --global user.name 'Cask Ops'" && \
  for project in ${COOPR_BUILD_PROJECTS} ; do \
    su coopr -c "bin/omnibus build ${project}" ; \
    rm -rf /opt/coopr ; \
  done
