#!/bin/bash
#
# Perform necessary coopr-ui setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p /var/log/coopr /var/run/coopr /etc/default /etc/logrotate.d
chown -R coopr:coopr /opt/coopr/ui
chown -R coopr:coopr /var/log/coopr
chown -R coopr:coopr /var/run/coopr

# Add defaults
if [ ! -f /etc/default/coopr-ui ] ; then
  echo "export COOPR_SERVER_URI=http://localhost:55054" > /etc/default/coopr-ui
  echo "export COOPR_LOG_DIR=/var/log/coopr" >> /etc/default/coopr-ui
  echo "export COOPR_UI_PORT=8100" >> /etc/default/coopr-ui
  echo "export COOPR_CORS_PORT=8081" >> /etc/default/coopr-ui
fi

ln -sf /opt/coopr/ui/distribution/etc/init.d/coopr-ui /etc/init.d/coopr-ui
cp -f /opt/coopr/ui/distribution/etc/logrotate.d/coopr-ui /etc/logrotate.d/coopr-ui

exit 0
