#!/bin/bash
#
# Perform necessary loom-provisioner setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p /var/log/loom /var/run/loom /etc/default /etc/logrotate.d /etc/loom/conf.dist /var/loom/data /etc/loom/conf.loom
chown -R loom:loom /etc/loom /opt/loom /var/loom /var/log/loom /var/run/loom

# Copy loom-server configs
cp -f /opt/loom/server/conf/* /etc/loom/conf.dist

# Copy default configuration (first time, only)
for i in $(cd /etc/loom/conf.dist ; ls -1) ; do
  if [ -e /etc/loom/conf.loom/${i} ] ; then
    continue
  else
    cp -f /etc/loom/conf.dist/${i} /etc/loom/conf.loom
  fi
done

# Add /etc/default files
if [ ! -f /etc/default/loom-provisioner ] ; then
  echo "export LOOM_NUM_WORKERS=5" > /etc/default/loom-provisioner
  echo "export LOOM_SERVER_URI=http://localhost:55054" >> /etc/default/loom-provisioner
  echo "export LOOM_LOG_DIR=/var/log/loom" >> /etc/default/loom-provisioner
  echo "export LOOM_LOG_LEVEL=info" >> /etc/default/loom-provisioner
fi
if [ ! -f /etc/default/loom-server ] ; then
  echo "export LOOM_LOG_DIR=/var/log/loom" > /etc/default/loom-server
  echo "# Uncomment the following to enable JMX metrics for Loom Server" >> /etc/default/loom-server
  echo "#export LOOM_JMX_OPTS=\"-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010" \
    "-Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false" \
    "-Dcom.sun.management.jmxremote.ssl=false\"" >> /etc/default/loom-server
  echo "# Uncomment the following to enable verbose GC logging" >> /etc/default/loom-server
  echo "#export LOOM_GC_OPTS=\"-verbose:gc -Xloggc:/var/log/loom/loom-server.gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1M\"" >> /etc/default/loom-server
  echo "# edit the following to add any other desired java options" >> /etc/default/loom-server
  echo "export LOOM_JAVA_OPTS=\"-XX:+UseConcMarkSweepGC -XX:+UseParNewGC \${LOOM_GC_OPTS} \${LOOM_JMX_OPTS}\"" >> /etc/default/loom-server
fi
if [ ! -f /etc/default/loom-ui ] ; then
  echo "export LOOM_SERVER_URI=http://localhost:55054" > /etc/default/loom-ui
  echo "export LOOM_LOG_DIR=/var/log/loom" >> /etc/default/loom-ui
  echo "export LOOM_UI_PORT=8100" >> /etc/default/loom-ui
fi

ln -sf /opt/loom/provisioner/bin/init-loom-provisioner /etc/init.d/loom-provisioner
ln -sf /opt/loom/provisioner/etc/logrotate.d/loom-provisioner /etc/logrotate.d/loom-provisioner
ln -sf /opt/loom/server/bin/init-loom-server /etc/init.d/loom-server
ln -sf /opt/loom/server/etc/logrotate.d/loom-server /etc/logrotate.d/loom-server
ln -sf /opt/loom/ui/bin/init-loom-ui /etc/init.d/loom-ui
ln -sf /opt/loom/ui/etc/logrotate.d/loom-ui /etc/logrotate.d/loom-ui

update-alternatives --install /etc/loom/conf loom-conf /etc/loom/conf.dist 10
update-alternatives --install /etc/loom/conf loom-conf /etc/loom/conf.loom 50

exit 0
